### ISSUE TITLE
why using offset hotpatching?

### ISSUE THREAD

**Issue by h0nIg** [mcafee/mysql-audit#105]
is there a reason why a hotpatching is done instead of just using the plugin architecture?
i'm discussing this with my colleague because we want to introduce an audit. but we have some serios doubts about using a memory modifiing plugin we have to update on every release (we are using ubuntu, but the offset structure may change on patches)

**Comment by guylichtman** [comment]
The offsets and hotpatching are two different things. The offsets are used to access data structures which we don't have access to via a consistent api. This allows us to distribute a single binary which can work with all existing versions of MySQL. By working with offsets there is no need to compile a different binary for each mysql version. The hotpatching is used to help to catch execution flows which the plugin api doesn't support. It mostly allows to catch table access as part of the audit flow.

**Comment by h0nIg** [comment]
Ok, regarding the offset stuff: is it 1) absolute possible 2) likely 3) not possible that with updates on ubuntu LTS the offset will be changed?
i would appreciate a more stable "connection" between the used version of mysql and the audit plugin. if we are going to use the audit plugin, an noob doing updates should not crash a production environment with a minor mysql update which will (most likely) fix security issues or major problems

**Comment by guylichtman** [comment]
It is possible that after an update the offsets will change. We validate the offsets during initialization and usually if the wrong offsets are used the plugin will simply not load, thus a crash is very unlikely because of wrong offsets. Additionally, there is a configuration option: `audit_checksum` which can be used for upgrade scenarios to limit the plugin to a specific binary build of mysql. So if you are paranoid about the upgrade scenario you can use `audit_checksum`. See: https://github.com/mcafee/mysql-audit/wiki/Configuration .

**Comment by guylichtman** [comment]
Closing issue. If you have any further questions feel free to open a new issue.
