### ISSUE TITLE
MYSQL for Windows - need the audit plugin? 

### ISSUE THREAD

**Issue by carlossaid** [mcafee/mysql-audit#110]
Hello,  I`m asking because the name of the modules to be downloaded, all of them have the name '%linux%' in someplace?  see: https://bintray.com/mcafee/mysql-audit-plugin/release

If you answer is yes, please Installation instructions?  

If I`m going to use just  McAfee Vulnerability  Assessment, not DAM, I need it?  

Thanks

**Comment by guylichtman** [comment]
The McAfee mysql audit plugin does not support windows. Only Linux is
supported.

For McAfee VA you do not need the audit plugin.

**Comment by carlossaid** [comment]
Thanks

**Comment by mstandfuss** [comment]
Is there any plans to release this for windows distribution in the future?

**Comment by aharonrobbins** [comment]
Hi.

Thanks for the note.

We currently have no plans to produce Windows builds of the plugin. However, since you can check out the source from Github, we expect that it should not be too hard to compile it yourself for Windows.

Thanks!

Aharon Robbins

Aharon (Arnold) Robbins
Senior Software Engineer
Sensor - Database Security
McAfee. Part of Intel Security.
[cid:image003.png@01CF5AF2.16A4D380]
