### ISSUE TITLE
Loggin Issue

### ISSUE THREAD

**Issue by Jamalc0m** [mcafee/mysql-audit#148]
Hello,

I have configured McAffe Mysql Audit  to log the attached records, but I found just few logs recored such, Connect, Quit, Failed and some SELECT queries that rans through command console SELECT user() example.
I would like to record the queries that runs through the application.
Thanks,

![img_0625](https://cloud.githubusercontent.com/assets/8554119/18658631/7bb286f4-7f0d-11e6-8832-74f2c92c0033.JPG)
![img_0627](https://cloud.githubusercontent.com/assets/8554119/18658632/7bb68808-7f0d-11e6-9554-b3563896a8f9.JPG)

**Comment by aharonrobbins** [comment]
Hi.  The default is to log everything, so you can try not setting audit_record_cmds at all. You should also remove the audit_json_socket_name and audit_json_socket settings, since you are logging just to a file.

You should probably also not set audit_record_objs and let the plugin default to recording all accessed objects (databases and tables).

Thanks,

Aharon

**Comment by Jamalc0m** [comment]
Hello @aharonrobbins,

Thanks thats work fine, I have one question regrading the size of the log file is there any way to customize the logs, for example if it reached some particular size it will create new file,
As in this way will effect the performance of the server.
Thanks,

**Comment by Jamalc0m** [comment]
Hello @aharonrobbins,

Any update ?

Thanks.

**Comment by aharonrobbins** [comment]
Hi. I'm glad things are working for you now.

There currently is no builtin mechanism for rotating the log file. However, see https://github.com/mcafee/mysql-audit/issues/140 which discusses how to do this with a cron job.

Thanks.
