### ISSUE TITLE
Json timestamp

### ISSUE THREAD

**Issue by bjayac** [mcafee/mysql-audit#190]
How to change the audit log time format from milli seconds to year/month/date:hours/minutes/seconds.

**Comment by aharonrobbins** [comment]
In src/audit_handler.cc in the functions start_msg_format and event_format, where it creates the "date" string, change it to format as you'd like.  The timestamp is in milliseconds.  Good luck.

**Comment by bjayac** [comment]
Hi

Iam not able to fetch below logs from mysql-audit.json logs... pls gudie me
how to add these.

Database Creation/ Deletion
User creation/Deletion

Also, pls let me know how to block user if  Password Failure for more than
3 times.


Thanks & Regards

Jaya Chandra B

**Comment by aharonrobbins** [comment]
Hi.

This issue is closed, I suggest you open a new one for your new inquiries.

Also, I cannot help you with your request.  McAfee moved development of their database security product to another site and this includes responsibility for the MySQL and PostgreSQL plugins.

I am no longer employed by them.

Best of luck,

Aharon Robbins
